core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_auth import views as user_auth_views

urlpatterns = [
    path('', user_auth_views.login_view, name='login'),
    path('auth/', include('user_auth.urls', namespace='user_auth')),
    path('dash/', include('dash.urls', namespace='dash')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

dash/urls.py
from django.urls import path
from . import views

app_name = "dash"

urlpatterns = [
    path('', views.dashboard, name='home'),
]

user_auth/urls.py
from .views import login_view, logout_view
from django.urls import path

app_name = 'user_auth'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

dash/models.py
from django.db import models

# Create your models here.

user_auth/models.py
from django.db import models

# Create your models here.

dash/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext as _
from django.http import JsonResponse

@login_required
def dashboard(request):
    """
    Render the dashboard page for authenticated users.
    """
    return render(request, 'dash/home.html')

user_auth/views.py
from django.shortcuts import render, redirect
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, JsonResponse
from django.urls import reverse, reverse_lazy


def login_view(request):
    if request.user.is_authenticated:
        return redirect('dash:home')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        try:
            if user is not None:
                login(request, user)
                return JsonResponse({'success': True, 'redirect_url': reverse('dash:home')})
            else:
                return JsonResponse({'success': False, 'errors': [_('Identifiants invalides')]})
        except Exception as e:
            return JsonResponse({'success': False, 'errors': [_(f'Une erreur est survenue {e}')]})
    return render(request, 'user_auth/login.html')

@login_required
def logout_view(request):
    """
    Déconnexion de l'utilisateur.
    """
    logout(request)
    return redirect('user_auth:login')

dash/templates/dash/home.html
{% extends "dash/index.html" %}
{% load static i18n %}


{% block dashContent %}
    <div class="container-fluid my-5">
        <div class="card">
            <div class="card-header">
                <h5 class="fw-semibold mb-0">List des requêtes</h5>
            </div>
            <div class="card-body">
                <p>Aucune requête trouvée, click le bouton ci-dessous pour en créer une.</p>
                <a href="#" class="btn btn-primary">Créer une requête</a>
            </div>
        </div>
    </div>
{% endblock dashContent %}

dash/templates/dash/index.html
{% extends "index.html" %}
{% load static %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet"
          href="{% static 'css/dash_index.css' %}?v={% now "U" %}" />
{% endblock css %}

{% block content %}
    <div class="account-actions">
        <a href="{% url 'user_auth:logout' %}"
           class="btn btn-danger position-fixed bottom-0 end-0 m-2 z-1">Se déconnecter</a>
    </div>
    {% block dashContent %}
    {% endblock dashContent %}
{% endblock content %}

templates/index.html
{% load static i18n %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {# Bootstrap #}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
              crossorigin="anonymous" />
        {# FontAwesome #}
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css"
              integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer" />
        {# Custom CSS #}
        <link rel="stylesheet" href="{% static 'css/index.css' %}?v={% now "U" %}" />
        {% block css %}
        {% endblock css %}
        {% block extra_css %}
        {% endblock extra_css %}
    </head>
    <body>
        {% block content %}
        {% endblock content %}

        {# Bootstrap JS #}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
                crossorigin="anonymous"></script>
        {# Custom Js #}
        <script src="{% static 'js/index.js' %}?v={% now "U" %}"></script>
        {% block js %}
        {% endblock js %}
        {% block extra_js %}
        {% endblock extra_js %}
    </body>
</html>

user_auth/templates/user_auth/login.html
{% extends "index.html" %}
{% load static i18n %}

{% block content %}
    <div class="container">
        <div class="m-auto shadow mt-5 p-4 bg-body rounded"
             style="max-width: 400px">
            <h2 class="fw-bold text-center">{% trans "Login" %}</h2>
            <ul id="errorList">
            </ul>
            <form method="post" action="{% url 'user_auth:login' %}" class="form">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <label for="username">{% trans "Username:" %}</label>
                    <input type="text"
                           class="form-control"
                           id="username"
                           name="username"
                           required />
                </div>
                <div class="form-group">
                    <label for="password">{% trans "Password:" %}</label>
                    <input type="password"
                           class="form-control"
                           id="password"
                           name="password"
                           required />
                </div>
                <button type="submit" class="btn btn-primary mt-3 w-75 d-block mx-auto">{% trans "Login" %}</button>
            </form>
        </div>
    </div>
{% endblock content %}